nengo/nengo-loihi

docs/installation.rst
docs/overview.rst
docs/tips.rst

It seems as though most people will be interacting with Loihi through the INRC superhost. Most of the docs are fine if you substitute INRC when we say "superhost" (it's likely a good thing for people to learn the term superhost well), but the installation instructions need to be different for a few reasons. Making a separate INRC section made more sense to me than making the generic superhost instructions have two possible paths. Also added INRC to the overview terminology and made some slight modifications in a few places. Also also added the IPython / Jupyter config thing that we had to do on the INRC to get it working.

Add INRC-specific docs

---

.gitignore
docs/examples.rst
docs/examples/neuron_to_neuron.ipynb
nengo_loihi/builder.py
nengo_loihi/loihi_cx.py
nengo_loihi/tests/test_connection.py
nengo_loihi/tests/test_ens_on_host.py
nengo_loihi/tests/test_ensemble.py

A notebook with three example networks using direct neuron-to-neuron connections. Here are the plots from the notebook if you don't want to run it yourself:
* Simple fan-out with Nengo
* Simple fan-out with Nengo Loihi
* One-to-one connections with Nengo
* One-to-one connections with Nengo Loihi
* Fixed probability connections with Nengo
* Fixed probability connections with Nengo Loihi
This was originally going to be part of #23 (and therefore is based on it), but I ran into an issue so I figured I would split this off into a separate PR so that it doesn't block the release (if we manage to figure it out in time though, we can include it).
The issue is that when making neuron-to-neuron connection in Nengo Loihi, the transform matrix has to be scaled up by `1 / dt` (at least, scaling up by …

Neuron to neuron examples

---

nengo_loihi/builder.py
nengo_loihi/tests/test_connection.py

@hunse suspected that #24 broke node to neuron and ensemble to neuron connections. We actually had a test for node to neuron connections and it worked fine, but we didn't ensemble to neuron connections. I added a test and they were indeed broken. In order to fix them, I reverted the dt scaling change in 751f8b6dbf97e830efcb403c20c00b3bde9137a7, but that caused `test_n2n_on_host` to fail again as those weights needed to be scaled up. Turns out that the connection from a `ChipReceiveNeurons` needed to be scaled up, as when I made that change all the tests passed. :crossed_fingers: we got most of the cases...

Fix dt scaling fix

---

nengo_loihi/simulator.py
setup.py

Addressing #31.
Removing the star expression allows the emulator to work with Python 3.4. The tests also all appear to pass on Python 2.7, though I did not add any `__future__` import statements, so it's not guaranteed e.g. division will work identically in Python 2.
I mostly use Python 3 now, so I'm happy to just merge this and only officially support Python 3 (but ideally all common versions of it) going forward. However, if you think Python 2 support is also good to have, speak up!
Also, I'm tempted to say we should either officially support Python 2, or check on import that we're using Python 3.

Compatibility with other python versions

---

nengo_loihi/builder.py

Before, this would just silently fail.

NotImplementedError for ensemble noise

---

nengo_loihi/builder.py
nengo_loihi/loihi_cx.py

With multiple connections into an ensemble, error if the the tau_s of one is different (and thus would overwrite) from that of the other.
Based on #42.
TODO: check that this doesn't break our existing recurrent networks (oscillator).

Do not overwrite filter

---

nengo_loihi/builder.py
nengo_loihi/neurons.py
nengo_loihi/tests/test_neurons.py

This rate function accounts for Loihi discretization.
TODO: I'd like to look qualitatively/quantitatively at how much effect this actually has on some more integrated test cases.
Just looking at `test_connection.py`, I found that `mean rmse: 0.99851 +/- 1.8416` before the change and `mean rmse: 0.90317 +/- 1.7610` after. So there's some improvement.
TODO: Once the ReLU fix is merged, I'll rebase and do the same for that.

Add more accurate LIF rate function for decoders

---

nengo_loihi/loihi_api.py

It will now be clear if a value (e.g. `vth`) is too small
or too large. Before, we lumped these two cases together.
This will help avoid some confusion, like that in #59.
`vth_to_manexp` now checks that `vth > 0` instead of `>= 0`.
This matches the validation done when using Loihi.

loihi_api: Split validation errors for clarity

---

nengo_loihi/simulator.py
nengo_loihi/tests/test_communication.py

This fixes the 4 hanging tests @drasmuss identified in https://github.com/nengo/nengo-loihi/commit/6ecae38ac28eac8fcf810bdcd73ff911cdd0eaf1
Those 4 tests now all pass with `precompute=False`
Fixes Issue #77  and Issue #6

Handle different refractory period in precompute=False spike probes

---

nengo_loihi/builder.py
nengo_loihi/tests/test_builder.py

As part of debugging #59 , @hunse noted that neurons with intercepts near 1 give very high gains, which makes those neurons vastly dominate the dynamic range of the fixed-point representation for the connection weights.  To address this, this PR puts an upper bound on the intercepts.  Any intercept above this limit is reduced to that limit.  In addition, to avoid unnatural clustering of intercepts at that bound, if the intercept distribution is given as a `nengo.dists.Uniform`, and the high value is above the limit, then it is reduced to the limit before sampling.
To illustrate the effects of this fix, here's a simple test model:
```python
model = nengo.Network()
with model:
stim = nengo.Node(lambda t: np.sin(t*2*np.pi))
ens = nengo.Ensemble(n_neurons=2000, dimensions=1)
output = …
```

Limit intercept values

---

CHANGES.rst
nengo_loihi/conftest.py
nengo_loihi/loihi_interface.py
nengo_loihi/tests/test_learning.py
nengo_loihi/tests/test_probe.py

This fixes the spike counter issue pointed out in #5.  Note that there are still some issues with random hanging in the test suite, but I think those are caused by being assigned to particular boards in the INRC cloud, rather than global state (rerunning the tests in the same way but landing on a different device fixes the problem, as opposed to earlier where the tests would deterministically fail at the same spot in the test suite).
I also added a `--no-hang` option to pytest, which will automatically skip tests that are known to hang on Loihi  (`pytest nengo_loihi --target loihi --no-hang`).  That way you can run the whole test suite at once, rather than having to stop and restart.

Reset spike probes

---

nengo_loihi/splitter.py
nengo_loihi/tests/test_splitter.py

This PR makes a quick change to the splitter system such that this:
```python
nengo.Connection(a.neurons, output, transform=w)
```
is the same as
```python
nengo.Connection(a, output, solver=nengo.solvers.NoSolver(w.T))
```
The main reason for this is that a) these two should be the same, and b) there's a nice sequence of tutorials @xchoo and I have planned that requires this syntax (we want to teach learning before teaching NEF-style decoders, to match more closely what typical neural network modellers are used to).

Move manual decoders onchip

---

docs/examples/node_ens_ens.py
nengo_loihi/builder.py
nengo_loihi/tests/test_connection.py
nengo_loihi/tests/test_ensemble.py
nengo_loihi/tests/test_examples.py
nengo_loihi/tests/test_learning.py
nengo_loihi/tests/test_probe.py
nengo_loihi/tests/test_radius.py

This would fix (for example) neuron->ensemble connections
(of which we currently have no test cases).
Unfortunately, this changes the behaviour of node->ensemble connections,
causing node_ens_ens to fail. The synapse set on the connection (None)
overrides the default INTER_TAU synapse, removing the filtering on
the ReLU neurons used to turn the node values into spikes.
Based on #43.

Always set filter on post ensemble in connection

---

conftest.py
nengo_loihi/loihi_cx.py
nengo_loihi/tests/test_loihi_cx.py

In strict mode, issues (like U/V overflows) will raise a SimulatorException. When not in strict mode, these issues will be raised as a warning. The default is not to be in strict mode, as issues do happen on occasion, but we run the test suite in strict mode to find issues early.
Addresses #88.

Add strict mode to emulator

---

docs/installation.rst
nengo_loihi/loihi_interface.py
nengo_loihi/simulator.py
nengo_loihi/tests/test_loihi_interface.py

Update `async` parameter to `aSync`. I left our parameter name as `async`.  We could update it, but since we're sticking to the Python convention of snake_case names I figured `async` was preferred.
Updated the installation instructions for the new workflow (and using conda for everything).  This removed the distinction between the INRC/Superhost installation steps, so I combined them.

Compatibility with NxSDK 0.7 release

---

nengo_loihi/loihi_interface.py
nengo_loihi/simulator.py
nengo_loihi/snips/nengo_io.c.template
nengo_loihi/snips/nengo_learn.c
nengo_loihi/tests/test_learning.py
nengo_loihi/tests/test_splitter.py

This PR fixes multidimensional learning.  It is based off of `move-manual-decoders-onchip`, but only because that had a nice test that fit for this PR.
All this does is fix the snip code and the communication code such that all the error data gets sent across and applied.  It doesn't change the emulator at all, since it was already working in the emulator.
The communication protocol is not wonderful.  The message format is `[core_id, n_vals, val_0, val_1, ... val_n-1]`, so the first two values are the same every time a message is sent (this isn't much worse than the old format, which was `[core_id, val_0]`).  Optimizing that will be a different PR, and will interact in interesting ways with #26 .  But this is a definite improvement in the meantime.
This is heavily based on, but replaces …

Multidimensional learning

---

nengo_loihi/loihi_interface.py

Two little bugs that I found when finding the 300 neuron hanging bug.
The first is just that we're counting the number of compartments wrong in loihi_interface. We need to add 1 to the last index to get the number.
The second I'm less sure about, but it looked wrong. It's that when we're sending spikes for precompute=True, we gather up all the spikes, and then send them all to the spike generator for the last input. As it happens, this isn't a problem right now, since all inputs share the same spike generator. But if we did change things so that they had their own generators, I think we'd want it as I have it here. I'd like @tcstewar to confirm this, though, since he wrote that code I think.

Fix number of compartments

---

CHANGES.rst
nengo_loihi/splitter.py
nengo_loihi/tests/test_connection.py

Previously passing a `Distribution` for a transform gave errors on chip->host and host->chip connections, this fixes that and adds a test.
Note that the way the seeding is done isn't strictly correct, because we don't have access to the connection seeds (since this is all occurring before the seeding happens in the builder).  But it has the same functional behaviour (deterministic output if a seed is set on the Network or Connection).
This fixes #65

Support Distributions on Connection transforms

---

CHANGES.rst
nengo_loihi/builder.py
nengo_loihi/splitter.py
nengo_loihi/tests/test_learning.py
nengo_loihi/tests/test_precompute.py
nengo_loihi/tests/test_splitter.py

@pblouw reported that his keyword spotting demo is broken in v0.3.0, and indeed [our keyword spotting example is broken also](https://www.nengo.ai/nengo-loihi/examples/keyword_spotting.html). He tracked it down to [this commit](https://github.com/nengo/nengo-loihi/commit/0811e2a840cf0c9bb24d77a10f43e6e3fc8a8486), which seems like it shouldn't even affect the keyword spotting network, but in fact it does.
The reason why that commit affects the keyword spotting network is that it translates **all** neuron->* connections in which `pre` is onchip and `post` is offchip with `transform=weights` to a `solver=NoSolver(weight.T)` connection. This would be fine if those two connections made no difference to how the network behaves, but that is unfortunately not the case, as evidenced by the keyword …

Fix keyword spotting example

---

nengo_loihi/builder.py
nengo_loihi/loihi_cx.py
nengo_loihi/tests/test_loihi_cx.py

Just a quick change, but as discussed in the meeting it might be worth addressing the fact that this makes the final model dependent on the build order (as it uses the final tau_s value).  Eventually we will support different tau_s values, but for now perhaps we should take the one with the longest time constant?

Modifying tau_s gives a warning, not an Exception

---

nengo_loihi/loihi_cx.py
nengo_loihi/tests/test_loihi_cx.py

On Loihi, spikes always take one timestep to get where they're going. With input spikes in the emulator, we were not accounting for that delay and having them arrive instantaneously. This PR fixes that.
Based off #111, so that I could update the test there to get rid of the delay.

Emulator input delay

---

CHANGES.rst
setup.py

The `snips` folder is included in our pypi release, but by default it doesn't get included in the installation when you actually `pip install nengo-loihi` (because it doesn't contain any python files).  This modifies `setup.py` to tell it to include the `snips` folder.

Include snips directory when building dist

---

.ci/test.sh
docs/index.rst
docs/troubleshooting.rst
nengo_loihi/builder.py
nengo_loihi/loihi_api.py
nengo_loihi/loihi_cx.py
nengo_loihi/loihi_interface.py
nengo_loihi/neurons.py
nengo_loihi/simulator.py
nengo_loihi/snips/nengo_io.c.template
nengo_loihi/tests/test_allocators.py
nengo_loihi/tests/test_neurons.py
setup.py

I realized that there's a number of fixes as part of the convnet stuff that are useful by themselves, and would be helpful for the work I'm doing now. Since it still could be a little while before the actual convnet PR is merged, I figured that this could be a separate PR. A lot of it is not directly related to convnets, it's just bugs I found or things I needed to fix as part of doing that work.

Convnet prep

---

.ci/test.sh
.gitignore
.travis.yml
CHANGES.rst
conftest.py
nengo_loihi/builder.py
nengo_loihi/loihi_cx.py
nengo_loihi/loihi_interface.py
nengo_loihi/simulator.py
nengo_loihi/splitter.py
nengo_loihi/tests/test_precompute.py
pytest.ini

This adds some additional options to `pytest.ini` which makes it possible to run the Nengo tests with
```bash
pytest --pyargs nengo
```
Most of the test failures I'm seeing right now (just running on the emulator) are due to issues already fixed in existing pull requests, so the number of passing tests isn't very meaningful.
Still todo:
[Additional discussion](https://gitter.im/nengo/loihi-48)

Enable running Nengo tests

---

conftest.py
nengo_loihi/builder.py
nengo_loihi/loihi_api.py
nengo_loihi/loihi_cx.py
nengo_loihi/loihi_interface.py
nengo_loihi/simulator.py
nengo_loihi/tests/test_learning.py
nengo_loihi/tests/test_loihi_cx.py
nengo_loihi/tests/test_testing.py

This refactors the host-to-chip and chip-to-host communication, so that LoihiSimulator and CxSimulator don't need to know anything about Nengo objects. This allows both simulators to work with general CxModels, making testing easier since we can create a custom CxModel and test it.
This is based off #121 and #133.

Communication refactoring

---

docs/examples/integrator.ipynb
docs/examples/integrator_multi_d.ipynb
nengo_loihi/passthrough.py
nengo_loihi/simulator.py
nengo_loihi/splitter.py
nengo_loihi/tests/test_learning.py
nengo_loihi/tests/test_passthrough.py
nengo_loihi/tests/test_simulator.py
nengo_loihi/tests/test_snips.py
nengo_loihi/tests/test_splitter.py

This PR gets rid of the passthrough Nodes between on-chip Ensembles.  They are replaced by Connections that do the same thing as those Nodes.  Without this PR, all passthrough Nodes are implemented on the host, which means a lot more communication between the host and the chip.  Also, removing these passthrough Nodes allows us to use precompute=True for networks with these intermediate passthrough Nodes.
The basic functionality works, but the main thing I still need to do here is write a *lot* of tests.  In particular, this is a completely different method for removing passthrough nodes than I've ever implemented before.  This method is a lot cleaner, I think, and I think it's much less prone to the weird edge-case problems that I've run into with previous implementations, but given that …

Remove passthrough nodes onchip

---

.codecov.yml

We won't require these checks to pass (as right now our CI can't cover the loihi hardware-specific code), but probably still useful to have the information readily displayed (and we would expect them to pass for things that don't touch the hardware).

Enable codecov status checks

---

CHANGES.rst
conftest.py
nengo_loihi/loihi_api.py
nengo_loihi/loihi_cx.py
nengo_loihi/neurons.py
nengo_loihi/tests/test_conv.py
nengo_loihi/tests/test_loihi_api.py
nengo_loihi/tests/test_neurons.py

Improving the accuracy of an integrator network. Fixes #114, namely an integrator using a recurrent weight connection.
The integrator network still does not work as expected when using a decoded (non-weight) connection (now documented in #125).

Integrator accuracy

---

CHANGES.rst
docs/examples/adaptive_motor_control.ipynb
nengo_loihi/allocators.py
nengo_loihi/builder.py
nengo_loihi/config.py
nengo_loihi/loihi_api.py
nengo_loihi/loihi_cx.py
nengo_loihi/loihi_interface.py
nengo_loihi/tests/test_learning.py
nengo_loihi/tests/test_loihi_api.py

This improves both the match between emulator and Loihi learning, and emulator and Nengo learning. The result is that everything matches Nengo better.
Based off of #137. Replaces #98.
TODO: I haven't tested this in extreme cases where we actually see overflow in the weights. I think some of these cases were referenced in #98. I (or someone) should look at these cases.

Learning matches Nengo learning more closely

---

CHANGES.rst
nengo_loihi/builder.py
nengo_loihi/simulator.py
nengo_loihi/splitter.py
nengo_loihi/tests/test_builder.py
nengo_loihi/tests/test_communication.py
nengo_loihi/tests/test_decode_neurons.py
nengo_loihi/tests/test_learning.py
nengo_loihi/tests/test_multiple.py
nengo_loihi/tests/test_passthrough.py
nengo_loihi/tests/test_splitter.py

This helps to address #129.
Rather than using homogeneous interneurons with noise, this uses heterogeneous interneurons. However, they are designed so that they all use the same decoder, which means that the size of encoders in target populations can remain small (otherwise it would scale with the number of interneurons).
Based off #124.

Interneuron improvements

---

nengo_loihi/simulator.py
nengo_loihi/tests/test_simulator.py

`False` is also a valid value to indicate no `Simulator.progress_bar`.
Currently, `pytry` passes `False` if no progress bar is requested, and because of this the benchmarks notebook is not working without this change.

Support other null values for progress_bar

---

.ci/static.sh
.gitlint

Uses `gitlint` to check for style on commit messages.  I added a bunch of example commits to verify that it catches the cases we want it to catch (see https://travis-ci.com/nengo/nengo-loihi/jobs/174091637#L1044).
I also changed our static check script back so that it runs all of the checks before exiting (rather than exiting immediately on error).  Particularly with the commit checking, it's helpful to see all of the commit message errors at once.
Also fixed an error in the `flake8` installation (unrelated to `gitlint`, just triggered by the new `flake8` release, but required to get the static checks passing again).

Apply style checks to commit messages

---

CHANGES.rst
nengo_loihi/inputs.py
nengo_loihi/simulator.py
nengo_loihi/splitter.py
nengo_loihi/tests/test_splitter.py

- Splitter preserves object order from original network.
- Host/chip receivers are always called in same order.
This makes sure that seeds are always set the same as well. Right now, setting a seed on a network does not actually guarantee it will be the same from one run to the next, because the splitter dictionaries change the order that everything gets built in in a non-deterministic way.

Ensure things happen in consistent order

---

CHANGES.rst
nengo_loihi/block.py
nengo_loihi/builder/ensemble.py
nengo_loihi/discretize.py
nengo_loihi/emulator/tests/test_emulator.py
nengo_loihi/hardware/interface.py
nengo_loihi/tests/test_neurons.py
nengo_loihi/tests/test_probe.py

This adds a test for neuron input (current) probes, which were not working correctly (due to negative values not being cast correctly, and integers not being filtered correctly). This also corrects both these issues.
TODO:

Test probes

---

CHANGES.rst
nengo_loihi/builder/probe.py
nengo_loihi/emulator/interface.py
nengo_loihi/tests/test_probe.py

Scalar probe weights occur when probing spikes, which was not being handled correctly in the `EmulatorInterface`. This is used in the CIFAR-10 notebook.

Fix bug with scalar probe weights

---

CHANGES.rst
docs/examples.rst
nengo_loihi/hardware/interface.py
nengo_loihi/hardware/nxsdk_objects.py
nengo_loihi/hardware/snips/nengo_io.c.template
nengo_loihi/tests/test_conv.py
nengo_loihi/tests/test_model.py
setup.py

This has CIFAR-10 running on Loihi. It replaces #117.
The main feature addition here is allowing population spikes on inputs. This allows us to re-use axons in the three-channel CIFAR-10 input images, making it much easier to get things on the chip.
A lot of these commits can probably be squashed together. The script in the sandbox should also be moved to the sandbox repository.

CIFAR-10 on Loihi

---

CHANGES.rst
nengo_loihi/simulator.py
nengo_loihi/tests/test_simulator.py

The GUI automatically tries to run with `progress_bar=True`, so raising a warning instead of an error allows the GUI to run successfully.

Raise warning instead of error for progress bars

---

.ci/hardware.sh
CHANGES.rst
nengo_loihi/hardware/interface.py
nengo_loihi/hardware/nxsdk_shim.py
nengo_loihi/hardware/snips/nengo_io.c.template
nengo_loihi/hardware/tests/test_simulator.py

Changes to support new NxSDK 0.8

Working with NxSDK 0.8

---

.ci/common.sh
.ci/conda.sh
.ci/docs.sh
.ci/emulator.sh
.ci/hardware.sh
.ci/static.sh
docs/conf.py

This is mainly relevant if these scripts are sourced, which happens for `conda.sh` on TravisCI. Once a script is sourced, the rest of the bash session will print all lines, which litters the TravsisCI log with internal commands that we can ignore like `travis_nanoseconds`.
This PR also gives a more informative error message if no command is passed to the script.

Unset bash settings after scripts

---

CHANGES.rst
nengo_loihi/compat.py
nengo_loihi/simulator.py
nengo_loihi/tests/test_simulator.py

This ensures that all object seeds are the same as for the corresponding reference Nengo model. It also ensures that seeds for all objects are set and the same whether precompute is True or False.
Depends on nengo/nengo#1476.
Computing the seeds before building, as I'm doing here, is something we've talked about adding to Nengo for a while. I would be open/happy to take the functionality here and move it to Nengo instead, since I think that is ultimately where we want it.

Seeds match Nengo

---

.ci/emulator.sh
.ci/hardware.sh
CHANGES.rst
nengo_loihi/block.py
nengo_loihi/builder/builder.py
nengo_loihi/builder/nengo_dl.py
nengo_loihi/builder/probe.py
nengo_loihi/builder/tests/test_nengo_dl.py
nengo_loihi/compat.py
nengo_loihi/decode_neurons.py
nengo_loihi/emulator/interface.py
nengo_loihi/hardware/builder.py
nengo_loihi/hardware/interface.py
nengo_loihi/hardware/nxsdk_objects.py
nengo_loihi/inputs.py
nengo_loihi/neurons.py
nengo_loihi/passthrough.py
nengo_loihi/simulator.py
nengo_loihi/splitter.py
nengo_loihi/tests/test_conv.py
nengo_loihi/tests/test_learning.py
nengo_loihi/tests/test_neurons.py
setup.py

This adds nengo_dl TensorFlow builders for the LoihiLIF and LoihiSpikingRectifiedLinear neuron types. This allows nengo_dl networks to train with tuning curves like those of the chip neurons, allowing for more accurate conversion of ANNs for the chip.
Based off #133

nengo_dl builders for Loihi neurons

---

CHANGES.rst
nengo_loihi/tests/test_connection.py
nengo_loihi/tests/test_conv.py
nengo_loihi/version.py

We had some empty plots again, so I fixed those in 1bf0cc6 and also noticed a test that we can probably re-enable now with the changes we've made. They pass on emulator, but wasn't sure about hardware, so I figured I'd make a PR and let TravisCI do that testing for me.
I included the two release commits here so that if this PR passes tests I can merge this in and then go back to the 0.6.0 release commit, push things to PyPI and tag it and all that once it's in master.

Release 0.6.0

---

nengo_loihi/__init__.py
nengo_loihi/simulator.py
nengo_loihi/tests/test_version.py
nengo_loihi/version.py

Check Nengo version for compatibility. 
- Error if Nengo version is too old
- Warn if Nengo version is newer than latest tested version
TODO:

Nengo version check

---

CHANGES.rst
nengo_loihi/hardware/allocators.py
nengo_loihi/hardware/builder.py
nengo_loihi/hardware/interface.py
nengo_loihi/hardware/nxsdk_objects.py
nengo_loihi/hardware/tests/test_allocators.py
nengo_loihi/hardware/tests/test_interface.py
nengo_loihi/simulator.py
nengo_loihi/tests/test_conv.py
nengo_loihi/tests/test_simulator.py

Abstracted two different methods of allocating resources to models:
- `OneToOne()` which is the same method as before (default)
- `RoundRobin(n_chips)` which cycles through chips per block / input
Ran the entire unit test suite with a manually-overwritten default of `allocator=RoundRobin(n_chips=8)` (on our local host; not shown) and discovered that all failed tests currently fall into one of two categories:
1. Convolutional weights (`pop[16|32]`) across chips
2. Use of SNIPS (`precompute=False`)
Multi-chip support is otherwise working and the user can override / customize the behaviour, with the following notes:
- `RoundRobin(n_chips)` gives _identical_ behaviour across any number of `n_chips` between `1` and `8` inclusive (unit-tested).
- Each failure mode currently returns an error …

Multi-chip support, testing, and failure modes

---

docs/setup/host-board.rst
nengo_loihi/neurons.py
nengo_loihi/tests/test_connection.py
nengo_loihi/tests/test_conv.py
nengo_loihi/tests/test_ensemble.py
nengo_loihi/tests/test_neurons.py
pytest.ini

The changes here break a number of nengo-loihi tests: https://github.com/nengo/nengo/pull/1437. Here we will fix them.

Accommodate new nengo.NeuronTypes.currents and .rates

---

.ci/hardware.sh.template
.nengobones.yml
CHANGES.rst
docs/examples/adaptive_motor_control.ipynb
nengo_loihi/builder/builder.py
nengo_loihi/builder/connection.py
nengo_loihi/builder/inputs.py
nengo_loihi/builder/node.py
nengo_loihi/builder/probe.py
nengo_loihi/builder/tests/test_connection.py
nengo_loihi/builder/tests/test_inputs.py
nengo_loihi/conv.py
nengo_loihi/emulator/interface.py
nengo_loihi/hardware/builder.py
nengo_loihi/hardware/nxsdk_shim.py
nengo_loihi/inputs.py
nengo_loihi/passthrough.py
nengo_loihi/simulator.py
nengo_loihi/splitter.py
nengo_loihi/tests/test_conv.py
nengo_loihi/tests/test_examples.py
nengo_loihi/tests/test_learning.py
nengo_loihi/tests/test_passthrough.py
nengo_loihi/tests/test_simulator.py
nengo_loihi/tests/test_splitter.py

Closes #80. Refactors the splitter logic for adding / removing connections to occur within the builder. This consolidates the connection logic into one place (`builder/connection.py`) so that backend-relevant logic and objects are manipulated at the same level of abstraction.
Overarching ideas:
- The splitter returns "directives" (i.e., sets of instructions) to guide the builder.
- The builder fills in all three "sub-models" (`self`, `host`, and `host_pre`) in parallel, by delegating the objects to the appropriate builder methods.
Solves the following bugs:
- https://github.com/nengo/nengo-loihi/issues/205 - Splitter handles sliced probes.
- https://github.com/nengo/nengo-loihi/issues/206 - Passthrough removal handles sliced probes.
- https://github.com/nengo/nengo-loihi/issues/207 - …

Splitter refactoring

---

.ci/hardware.sh.template
.nengobones.yml
.travis.yml
CHANGES.rst
docs/installation.rst
nengo_loihi/builder/tests/test_connection.py
nengo_loihi/emulator/tests/test_interface.py
nengo_loihi/hardware/interface.py
nengo_loihi/hardware/nxsdk_shim.py
nengo_loihi/hardware/snips/nengo_io.c.template
nengo_loihi/hardware/tests/test_allocators.py
nengo_loihi/hardware/tests/test_interface.py
nengo_loihi/tests/test_conv.py
nengo_loihi/tests/test_learning.py
nengo_loihi/tests/test_version.py

The first commit makes our `pytest.raises` checks more strict. This is something I was using to debug, and isn't strictly needed by this PR, but IMO is a good thing to do.
The second commit localizes the `os.chdir` to be within a `try-finally` block. This avoids a really weird issue we were seeing as a part of #217 (e.g., [see this job](https://travis-ci.com/nengo/nengo-loihi/jobs/195940847) and look for `nengo_loihi/hardware/tests/test_allocators.py::test_block_size`).
Essentially... if an error happens when the model is being built, then the current working directory (cwd) is permanently changed. More specifically, an error occurs within `HardwareInterface.__init__`, and so `__exit__` is never invoked. As a result, the directory is never changed back. This only occurs for `--target …

Fix travis CI

---

.nengobones.yml
CHANGES.rst
nengo_loihi/builder/connection.py
nengo_loihi/builder/tests/test_connection.py
nengo_loihi/tests/test_connection.py
setup.cfg

An alternative to #71.
In #71, I feel like I cheated, and specifically implemented neurons->ensemble connections that only have a scalar transform. In that case, the dimensionality of the post-ensemble has to be the same as the pre neurons.
In this PR, I do it in a more general way, by including interneurons in the case when we're connecting from neurons to ensemble. This allows us to put arbitrary transforms in there.
HOWEVER, I did find that for the case where we have neurons->ensemble connections of the first type, with scalar transforms, this new method does not work well. I think that's because each group of interneurons (i.e. each dimension in the interneurons population) is being driven only by one input neuron, so its input is very noisy and it just doesn't perform well. …

Neurons to ensemble connections with interneurons

---

.nengobones.yml
CHANGES.rst
nengo_loihi/builder/connection.py
nengo_loihi/config.py
nengo_loihi/tests/test_connection.py
nengo_loihi/tests/test_learning.py
nengo_loihi/tests/test_simulator.py
setup.cfg

In #73, we started talking about whether the current defaults are actually the best. I chose them pretty arbitrarily, so it's unlikely that they are.
This PR is a place for us to collect changes to the defaults that improve performance across a variety of models. With many of the Nengo benchmarks now becoming available, those could be a good way to test potential changes. 
To start, I'm correcting something that was a mistake on my part. Since intercepts happen after encoders, we actually just need to lower the upper bound on intercepts (away from one) to avoid high gains. The lower bound can (and I think should) stay at -1. I'd like to test this change on some benchmarks, though, to see if it's actually better.
EDIT: I just went and rebased this to the `integrator-accuracy` branch …

Configure defaults for optimal Loihi performance

---

.nengobones.yml
.templates/hardware.sh.template
nengo_loihi/hardware/interface.py
nengo_loihi/hardware/nxsdk_shim.py
setup.cfg

The only change from what we had before is that we now do the rendering of the snip template files in a temporary directory (to ensure we don't have multiple simulators trying to write to the same file).  Ran the CI build a bunch of times (see https://travis-ci.com/nengo/nengo-loihi/builds) and didn't see any problems.  Hard to say for sure with these race conditions, I'll keep running it some more, but seems good 🤷‍♂ .

Re-enable parallel hardware tests

---

.nengobones.yml
.travis.yml
CHANGES.rst
nengo_loihi/hardware/interface.py
nengo_loihi/hardware/nxsdk_shim.py
nengo_loihi/hardware/tests/test_interface.py

Support the newest NxSDK in a non-backwards-compatible way. The new NxSDK adds a number of features that we plan on taking advantage of, and supporting both new and old seems like an extra burden.
NOTE: Do not merge this until AFTER the next release, so that we have a released nengo_loihi (0.7.0) that works with NxSDK 0.8.0/1.

Support NxSDK 0.8.5

---

CHANGES.rst
nengo_loihi/block.py
nengo_loihi/builder/connection.py
nengo_loihi/builder/tests/test_connection.py
nengo_loihi/emulator/interface.py
nengo_loihi/hardware/builder.py
nengo_loihi/hardware/interface.py
nengo_loihi/hardware/tests/test_allocators.py
nengo_loihi/hardware/tests/test_interface.py
nengo_loihi/tests/test_connection.py
nengo_loihi/tests/test_conv.py
nengo_loihi/tests/test_simulator.py

Allow population spikes between chips. This allows convolutional connections from chip to chip.

Multi-chip population spikes

---

.nengobones.yml
CHANGES.rst
nengo_loihi/block.py
nengo_loihi/builder/connection.py
nengo_loihi/builder/sparse_matrix.py
nengo_loihi/builder/tests/test_connection.py
nengo_loihi/builder/tests/test_sparse_matrix.py
nengo_loihi/compat.py
nengo_loihi/decode_neurons.py
nengo_loihi/discretize.py
nengo_loihi/emulator/interface.py
nengo_loihi/emulator/tests/test_interface.py
nengo_loihi/hardware/builder.py
nengo_loihi/hardware/interface.py
nengo_loihi/hardware/nxsdk_objects.py
nengo_loihi/hardware/tests/test_allocators.py
nengo_loihi/hardware/tests/test_interface.py
nengo_loihi/tests/test_connection.py
nengo_loihi/tests/test_conv.py
nengo_loihi/tests/test_validate.py
setup.cfg
setup.py

Support `Sparse` transforms for on-chip connections.
Also uses sparse matrices when possible for node->neuron and neuron->neuron connections that have a scalar or diagonal transform.

Implement Sparse transforms

---

nengo_loihi/builder/connection.py
nengo_loihi/compat.py
nengo_loihi/tests/test_connection.py
nengo_loihi/tests/test_conv.py
nengo_loihi/tests/test_examples.py
nengo_loihi/tests/test_nxsdk_obfuscation.py

This adds the test described in #63, with some additional filtering (Nengo Loihi drifts a little bit over time) and with an assertion at the end.
It's based on #247, which should be merged first.
As this just adds a test, I don't believe it needs a changelog entry.

Add test for input synapses

---

.nengobones.yml
.travis.yml
CHANGES.rst
docs/installation.rst
nengo_loihi/hardware/builder.py
nengo_loihi/hardware/interface.py
nengo_loihi/hardware/nxsdk_shim.py
nengo_loihi/hardware/tests/test_interface.py

Support NxSDK 0.9.0. No changes are actually required, but we now do not warn for and test against 0.9.0.
I also updated `HardwareInterface` to store the min and max NxSDK versions on the class, so these can be checked. We now no longer have to remember to update the test in `hardware/tests/test_interface.py` each time we change the NxSDK version.
Depends on #234.

NxSDK 0.9.0

---

CHANGES.rst
docs/examples.rst
docs/examples/lmu.ipynb

This is literally a copy of the Nengo core example, with some additional text to note that this runs on Loihi, and with some changes to parameters to make it run in a reasonable amount of time with reasonable performance. I also bumped up the learning rate a bit and upped `pes_error_scale` to be able to get decent performance running for only 30 simulated seconds. It still might take a bit too long on the emulator for TravisCI, but we'll see. I haven't tried running it on the board yet, but I'll do that next.
For reference, [here are the plots you get at the end with Nengo core](https://www.nengo.ai/nengo/examples/learning/lmu.html) and below are the plots I got running this on the emulator:
I'll post the plots from the chip when I have them.

Add LMU example

---

CHANGES.rst
nengo_loihi/block.py
nengo_loihi/emulator/interface.py
nengo_loihi/hardware/builder.py
nengo_loihi/hardware/nxsdk_objects.py
nengo_loihi/tests/test_block.py
nengo_loihi/tests/test_connection.py

Some arrays have shape `(1, 0)` which gives them a length of 1, but no size.

Fix bug with no inputs to a neuron

---

CHANGES.rst
nengo_loihi/block.py
nengo_loihi/builder/connection.py
nengo_loihi/config.py
nengo_loihi/conv.py
nengo_loihi/emulator/interface.py
nengo_loihi/hardware/builder.py
nengo_loihi/hardware/interface.py
nengo_loihi/hardware/nxsdk_objects.py
nengo_loihi/hardware/snips/nengo_io.c.template
nengo_loihi/splitter.py
nengo_loihi/tests/test_block.py
nengo_loihi/tests/test_connection.py
nengo_loihi/tests/test_conv.py
nengo_loihi/tests/test_splitter.py
nengo_loihi/validate.py

We were having problems with dummy axons still doing something on the chip, even though they shouldn't. This PR fixes that. I added the test in a separate commit first, so that it's easy to confirm the test fails before the fix and passes after it.
The latter two commits improve support for population axons. The first one allows users to make a connection use pop16 axons instead of the default pop32. This uses fewer axon slots, so that connections can have more axons, but adds some constraints to how these axons are used. (In convolutional networks, this functionally amounts to having to use numbers of filters that are a multiple of 4, with `channels_last=True`. This allows the axon compartment offset ("base") to be a multiple of 4, which is the requirement for pop16. We could make copies …

Dummy axons work properly on chip

---

.travis.yml
CHANGES.rst
docs/conf.py
nengo_loihi/builder/connection.py
nengo_loihi/builder/nengo_dl.py
nengo_loihi/builder/tests/test_nengo_dl.py
nengo_loihi/compat.py
nengo_loihi/neurons.py
nengo_loihi/passthrough.py
nengo_loihi/simulator.py
nengo_loihi/tests/test_conv.py
nengo_loihi/tests/test_splitter.py
nengo_loihi/version.py

This insures that the NengoDL neuron builders are added even if
a `nengo_loihi.Simulator` has not yet been created (e.g. if they're
being used for training in NengoDL first).
Fixes #248.

Install NengoDL neuron builders on neuron init

---

.nengobones.yml
CHANGES.rst
nengo_loihi/builder/tests/test_connection.py
nengo_loihi/compat.py
nengo_loihi/config.py
nengo_loihi/hardware/interface.py
nengo_loihi/hardware/nxsdk_shim.py
nengo_loihi/tests/test_block.py
nengo_loihi/tests/test_conv.py
nengo_loihi/tests/test_simulator.py
setup.cfg
setup.py

This is the commit from #266 supporting the next version of NxSDK. Since we're not sure when that next version will be released, I separated it out into a separate PR to deal with later.

Support NxSDK 0.9.1

---

CHANGES.rst
nengo_loihi/builder/probe.py
nengo_loihi/builder/split_blocks.py
nengo_loihi/hardware/nxsdk_objects.py
nengo_loihi/tests/test_probe.py

- Wrong index used for slice in `split_probe`.
- `compartment_idxs` must be an array to allow `probe.slice`
to be an index array in `hardware.builder.build_probe`.
- Probe weights were not configured properly when the probe target
was an `ObjView`.

Fix split/sliced probe bugs

---

CHANGES.rst
nengo_loihi/builder/split_blocks.py
nengo_loihi/config.py
nengo_loihi/hardware/builder.py
nengo_loihi/tests/test_config.py

Add an error if the block shape does not match the ensemble number of neurons. Fixes #285.
Also adds an error if extra atom bits are used with pop16 axons on hardware, since this is not yet implemented in NxSDK.

Block size error

---

CHANGES.rst
docs/examples.rst
docs/examples/keras-to-loihi.ipynb
nengo_loihi/tests/test_conv.py

Would appreciate comments! At this point I would wait for https://github.com/nengo/nengo-dl/issues/146 to be addressed and then finish up the last block, show it actually running on loihi and call it good. Thoughts?

Added keras-to-loihi IPython notebook example

---

docs/examples/keras-to-loihi.ipynb

The conversion using `scale_firing_rates` for each layer was giving 2% accuracy, it was caused by not scaling the additional `dense0` layer that was added due to Loihi constraints on spike probes. In fixing this, it made sense to add another subplot with the output from this layer, which then prompted the height of the plots to increase.
Fixed a couple of typos and an error that arose in plotting when there was no activity in any neurons in an ensemble.
Also added a line mentioning SNNs are better suited to temporal problems like video processing over still frames.

fixup! Add Keras-to-Loihi example

---

.nengobones.yml

For compatibility with the tensorflow<2.4 requirement added in https://github.com/nengo/nengo-loihi/pull/304.

Limit tensorflow-probability to <0.12

---

.nengobones.yml
.travis.yml
CHANGES.rst
nengo_loihi/dvs.py
nengo_loihi/hardware/interface.py
nengo_loihi/hardware/nxsdk_objects.py
nengo_loihi/tests/test_dvs.py
nengo_loihi/version.py
setup.py

I tested some older NxSDK versions. We were failing on 0.8.7 because some of the SNIP communication stuff doesn't work with that, so I've just dropped support for 0.8.7. Everything works on 0.9.0. (Except `test_conv_deepnet`, but that's an expected failure, since there's some population axon stuff that's been fixed in a more recent NxSDK. We actually used to skip that test on older NxSDK, but that got removed at some point. We could re-add an xfail or something, but it didn't seem worth it since we only ever run these tests on older NxSDK manually on a release.)
I also found some of the DVS stuff didn't work with older python/NxSDK, so I've fixed that. Also fixed some inconsistent naming of the `format` argument for DVS file format (I know `format` is a built-in, but I've never seen us …

Release candidate 1.0.0

---

CHANGES.rst
nengo_loihi/builder/builder.py
nengo_loihi/builder/inputs.py
nengo_loihi/builder/node.py
nengo_loihi/simulator.py
nengo_loihi/tests/__init__.py
nengo_loihi/tests/test_simulator.py

To address #311. 
TODO:
Test script:
This can also be run with `run_steps` commented out to test for builder memory leaks.
```
import gc
import nengo
import nengo_loihi
import numpy as np
from guppy import hpy
h = hpy()
class NewClass:
def __init__(self):
self.input_size = 10
self.n_neurons = 500
self.initialize_nengo()
def initialize_nengo(self):
network = nengo.Network()
with network:
def input_func(t):
return np.ones(10)
def output_func(t, x):
self.output = x
input_layer  = nengo.Node(output=input_func, size_in=0, size_out = self.input_size)
ensemble     = nengo.Ensemble(n_neurons=self.n_neurons, dimensions=1 )
output_layer = nengo.Node(output=output_func, size_in=self.n_neurons, size_out=0)
conn_in  = nengo.Connection(input_layer, ensemble.neurons, …
```

Fix memory leaks

---

CHANGES.rst
nengo_loihi/emulator/interface.py
nengo_loihi/emulator/tests/test_interface.py
nengo_loihi/hardware/interface.py
nengo_loihi/probe.py
nengo_loihi/simulator.py
nengo_loihi/tests/test_block.py
nengo_loihi/tests/test_conv.py
nengo_loihi/tests/test_probe.py
nengo_loihi/tests/test_simulator.py

Clear probes

---

CHANGES.rst
nengo_loihi/block.py
nengo_loihi/builder/connection.py
nengo_loihi/builder/discretize.py
nengo_loihi/builder/ensemble.py
nengo_loihi/builder/probe.py
nengo_loihi/builder/tests/test_discretize.py
nengo_loihi/builder/validate.py
nengo_loihi/hardware/builder.py
nengo_loihi/hardware/tests/test_interface.py
nengo_loihi/passthrough.py
nengo_loihi/simulator.py

It is almost always the case that a BuildError is associated with
building a particular object, and specifying the object makes it
easier to track down.

BuildErrors specify an object

---

.nengobones.yml
.pre-commit-config.yaml
.templates/hardware.sh.template
.travis.yml
CHANGES.rst
conftest.py
nengo_loihi/builder/connection.py
nengo_loihi/conv.py
nengo_loihi/hardware/nxsdk_shim.py
nengo_loihi/tests/__init__.py
nengo_loihi/tests/test_conv.py
nengo_loihi/tests/test_dvs.py
nengo_loihi/tests/test_learning.py
setup.cfg

This allows `"same"` padding to be used with `nengo.Convolution`. 
TODO:

Allow 'same' padding for convolution

---

.nengobones.yml
.templates/hardware.sh.template
CHANGES.rst
conftest.py
nengo_loihi/block.py
nengo_loihi/builder/builder.py
nengo_loihi/builder/connection.py
nengo_loihi/builder/discretize.py
nengo_loihi/builder/ensemble.py
nengo_loihi/builder/network.py
nengo_loihi/builder/split_blocks.py
nengo_loihi/builder/tests/test_builder.py
nengo_loihi/builder/validate.py
nengo_loihi/conv.py
nengo_loihi/decode_neurons.py
nengo_loihi/emulator/tests/test_interface.py
nengo_loihi/hardware/allocators.py
nengo_loihi/hardware/builder.py
nengo_loihi/hardware/interface.py
nengo_loihi/hardware/snips/nengo_host.cpp.template
nengo_loihi/hardware/snips/nengo_io.c.template
nengo_loihi/hardware/tests/test_allocators.py
nengo_loihi/hardware/tests/test_interface.py
nengo_loihi/tests/test_conv.py
nengo_loihi/tests/test_decode_neurons.py
nengo_loihi/tests/test_learning.py
nengo_loihi/tests/test_passthrough.py
nengo_loihi/tests/test_simulator.py
setup.cfg
setup.py

This is a culmination of a number of improvements made for a team-robot vision project:
- Speed ups for block splitting code
- Properly pass `dt` for preset DecodeNeurons, which allows `dt` to be changed for them.
- Save info from `discretize_block` so that users can make use of this if need be.
- Speed up build process.
- Reduce memory required for build, and use the nengo `float_dtype` to allow users to further reduce memory by setting this to e.g. float32 instead of the default float64.
- Add `GreedyComms` and `PartitionComms` allocators, which both aim to reduce inter-chip communication.
Based off #300.

team-robot vision project improvements

---

LICENSE.rst
docs/conf.py
nengo_loihi/builder/inputs.py
nengo_loihi/builder/node.py
nengo_loihi/emulator/tests/test_interface.py
nengo_loihi/inputs.py
nengo_loihi/tests/test_block.py
nengo_loihi/tests/test_simulator.py

Clears intermediary values as we consume them, freeing up memory (particularly when `run_steps` is called more than once). Addresses #323.

Clear spikes
